version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/aws_codedeploy_demo
permissions:
   - object: /var/www/html/aws_codedeploy_demo
     pattern: "**"
     owner: ubuntu
     group: www-data
     mode: 775
     type:
      - directory
      - file
