version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     mode: 775
     owner: www-data	
     group: www-data
     type:
       - directory
   - object: /var/www/html
     pattern: "**"
     mode: 775
     owner: www-data	
     group: www-data
     type:
       - file
hooks:
  ValidateService:
    - location: scripts/startapache.sh
      timeout: 300
      runas: root
